name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */12 * * *"

  # This command allows us to manually trigger the workflow from the Actions tab.
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the repository (update to v3 to avoid Node.js warnings)
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate the snake animation (no gif/svg output paths needed)
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: NimeshHansaka  # Replace with your GitHub username

      # Display the status of the repository
      - name: Show Status
        run: git status

      # Push changes to the output branch
      - name: Push Changes to Output Branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      # Publish the generated files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

